version: "3.8"
services:
  flask-app:
    build:
      context: ./flask-app/.
      dockerfile: Dockerfile
    ports:
     - target: 5500
       published: 5500
    networks:
      - nginx-flask
  db:
    build:
      context: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=flask-db
    networks:
      - nginx-flask
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - target: 80
       published: 80
         #volumes:
      #- source: ./nginx/nginx.conf
      # target: /etc/nginx/nginx.conf
    networks:
    - nginx-flask   

networks:
  nginx-flask:
